name: Cron

on:
  schedule:
    - cron: '0/6 * * * *' # Runs everyday at 6AM
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Commit README.md
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add README.md
        git commit -m "Update README.md"
        git push -f
