name: Organization Cron

on:
  schedule:
    - cron: '0/6 * * * *'  # Runs every 6 minutes.

jobs:
  cron_job:
    name: Run Cron Job
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Modify README.md
        run: |
          # Here you can add any script or command to modify your README.md file
          echo "This is an automated commit." >> README.md

      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Automated commit - $(date)"
        
      - name: Push changes
        run: |
          git push -f
